### ISSUE TITLE
[NoMic] Add ability to map text channels to voicechannels and generate on the fly

### ISSUE THREAD

**Issue by SteZZz** [Dav-Git/Dav-Cogs#50] opened 2020-07-15 17:42 UTC
I would like to suggest a feature to NoMic.
the ability to have text channels being created when joining a voice channel.
we already done some brainstorming through DM. but it is also nice to have some things written down.

I am using a cog names roomtools. and this auto creates voice channels according to the name of the game you are playing. you will join a voice channel and right after it will will create a new voice channel. you can find the cog here https://github.com/mikeshardmind/SinbadCogs#roomtools

* create text channel ones you join a voice channel.
* remove text channel when voice channel is empty / only see the text channel when you join the voicechannel
* limit the behavior to 1 or more categories (for me 1 would be enough).

**Comment by Dav-Git** [comment] 2020-07-27 22:05
Hey @SteZZz I have just been informed that this issue is a duplicate of what https://github.com/zephyrkul/FluffyCogs/ ``invoice`` cog does. I will be closing this issue in favor of the other cog.

**Closed by Dav-Git** 2020-07-27 22:05 UTC
Labels: Work in progress, feature
